### ISSUE TITLE
Bad Repo

### ISSUE THREAD

**Issue by pojavluncher2021** [carey036/modify_magisk_for_k40g#2]
What a big shame for this one

**Comment by carey036** [comment]
why

**Comment by carey036** [comment]
> What a big shame for this one

the offical magisk can not be used in k40g and n10p, they can use this version temporarily and wait for the official update.

I also contacted the official to locate this problem.

Is there any problem?

**Comment by carey036** [comment]
> Just because to not customize itself, They may add their own way, I have a Redmi 9c and f1vm is better than magisk and your shameful repository, Go delete it and never look at magisk again, Just use f1vm, it's kindness, that's just what. you need to stop using magisk and get f1vm 64 or 32bit

What the hell? Why should I listen to you? I use whatever I like
